---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check whether postfix is installed
  fail:
    msg: "Please install Postfix first."
  when: ansible_facts.packages['postfix'] | length != 1

- name: Check current postfix_exporter version
  command: "{{ postfix_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: postfix_exporter_version_check

- name: Create postfix_exporter user
  user:
    name: postfix_exporter
    groups: postfix, postdrop, adm
    shell: /sbin/nologin
    state: present

- name: Copy postfix_exporter into location
  ansible.builtin.get_url:
    url: "https://github.com/chas0amx/postfix_exporter/releases/download/GLIBC_2.32/postfix_exporter"
    dest: "/usr/local/bin/postfix_exporter"
    owner: postfix_exporter
    group: root
    mode: '0770'  # Set the file permissions to be executable
  when: postfix_exporter_version_check.stdout | length == 0
  # copy:
  #   src: files/postfix_exporter
  #   dest: /usr/local/bin/postfix_exporter
  #   owner: postfix_exporter
  #   group: root
  #   mode: '0770'
  # when: postfix_exporter_version_check.stdout | length == 0

- name: Copy the postfix_exporter systemd unit file
  template:
    src: postfix_exporter.service.j2
    dest: /etc/systemd/system/postfix_exporter.service
  register: postfix_exporter_service

- name: Reload systemd daemon if unit file is changed
  systemd:
    daemon_reload: true
  notify: restart postfix_exporter
  when: postfix_exporter_service is changed

- name: Ensure postfix_exporter is running and enabled at boot.
  service:
    name: postfix_exporter
    state: "{{ postfix_exporter_state }}"
    enabled: "{{ postfix_exporter_enabled }}"

- name: Verify postfix_exporter is responding to requests
  uri:
    url: http://localhost:9154
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
